export {
  useContentStats,
  useCreateContentStat,
  useUpdateContentStat,
  useDeleteContentStat,
  useMethodologySteps,
  useCreateMethodologyStep,
  useUpdateMethodologyStep,
  useDeleteMethodologyStep,
  useSiteSetting,
  useUpdateSiteSetting,
  useAdminServices,
  useCreateService,
  useUpdateService,
  useDeleteService,
  useAdminTestimonials,
  useCreateTestimonial,
  useUpdateTestimonial,
  useDeleteTestimonial,
  contentKeys,
} from "./services/content.service";
