export const ENVS_VARIABLES = {
  PORT: process.env.PORT,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
  NODE_ENV: process.env.NODE_ENV,
  SESSION_SECRET: process.env.SESSION_SECRET,
  PRIVATE_OBJECT_DIR: process.env.PRIVATE_OBJECT_DIR,
  PUBLIC_OBJECT_SEARCH_PATHS: process.env.PUBLIC_OBJECT_SEARCH_PATHS,
  LOG_LEVEL: process.env.LOG_LEVEL,
}
