/**
 * Cleanup S3 Duplicates
 *
 * Deletes the stale site-images/home/ keys that were generated by an
 * older version of the upload script (band-1.jpg, collage-1.jpg, etc.)
 * while keeping the current correct keys (band1.jpg, collage1.jpg, etc.).
 *
 * Run: npx tsx --env-file=.env scripts/cleanup-s3-duplicates.ts
 */

import "dotenv/config";
import {
  S3Client,
  DeleteObjectsCommand,
  ListObjectsV2Command,
} from "@aws-sdk/client-s3";

const client = new S3Client({
  region: process.env["AWS_S3_REGION"] ?? "us-east-1",
  credentials: {
    accessKeyId: process.env["AWS_ACCESS_KEY_ID"] ?? "",
    secretAccessKey: process.env["AWS_SECRET_ACCESS_KEY"] ?? "",
  },
});

const bucket = process.env["AWS_S3_BUCKET"] ?? "";

// Keys actively used by the current upload script (correct versions to KEEP)
const ACTIVE_KEYS = new Set([
  // site-images/home
  "site-images/home/hero-panel.jpg",
  "site-images/home/band1.jpg",
  "site-images/home/band2.jpg",
  "site-images/home/band3.jpg",
  "site-images/home/pillar1.jpg",
  "site-images/home/pillar2.jpg",
  "site-images/home/pillar3.jpg",
  "site-images/home/engage1.jpg",
  "site-images/home/engage2.jpg",
  "site-images/home/engage3.jpg",
  "site-images/home/collage1.jpg",
  "site-images/home/collage2.jpg",
  "site-images/home/collage3.jpg",
  "site-images/home/collage4.jpg",
  // site-images/services
  "site-images/services/mosaic-left.jpg",
  "site-images/services/mosaic-right.jpg",
  // site-images/government
  "site-images/government/hero-image.jpg",
  "site-images/government/main-left.jpg",
  "site-images/government/main-right.jpg",
  // projects/images
  "projects/images/rwanda-smart-grid.jpg",
  "projects/images/mozambique-lng-roads.jpg",
  "projects/images/lagos-healthcare.jpg",
  "projects/images/nairobi-water.jpg",
  "projects/images/sahel-solar.jpg",
  "projects/images/lamu-port.jpg",
  // services/images
  "services/images/government-advisory.jpg",
  "services/images/contracting-procurement.jpg",
  "services/images/project-development.jpg",
  "services/images/funding-advisory.jpg",
  "services/images/project-management.jpg",
  "services/images/market-entry.jpg",
]);

async function main() {
  console.log("🔍 Listing all S3 objects...\n");

  const res = await client.send(new ListObjectsV2Command({ Bucket: bucket }));
  const all = (res.Contents ?? []).map((o) => o.Key ?? "");

  const toDelete = all.filter((key) => {
    // Never delete user uploads (not managed by seed scripts)
    if (key.startsWith("uploads/")) return false;
    if (key.startsWith("branding/")) return false;
    if (key.startsWith("team/")) return false;
    if (key.startsWith("testimonials/")) return false;
    // Delete anything in seeded folders that isn't in ACTIVE_KEYS
    return !ACTIVE_KEYS.has(key);
  });

  if (toDelete.length === 0) {
    console.log("✅ No duplicate or stale keys found — bucket is clean.");
    process.exit(0);
  }

  console.log(`Found ${toDelete.length} stale key(s) to delete:\n`);
  toDelete.forEach((k) => console.log(`  ✗  ${k}`));

  const { Deleted, Errors } = await client.send(
    new DeleteObjectsCommand({
      Bucket: bucket,
      Delete: { Objects: toDelete.map((Key) => ({ Key })), Quiet: false },
    }),
  );

  console.log(`\n✅ Deleted ${Deleted?.length ?? 0} object(s)`);

  if (Errors && Errors.length > 0) {
    console.error("\n⚠ Errors:");
    Errors.forEach((e) => console.error(`  ${e.Key}: ${e.Message}`));
  }

  // Print final bucket state
  const res2 = await client.send(new ListObjectsV2Command({ Bucket: bucket }));
  const remaining = (res2.Contents ?? []).map((o) => o.Key ?? "").sort();
  console.log(`\n📦 Remaining objects (${remaining.length}):`);
  remaining.forEach((k) => console.log(`  ${k}`));

  process.exit(0);
}

main().catch((err) => {
  console.error("❌ Cleanup failed:", err);
  process.exit(1);
});
